[versions]
agp = "8.1.0"
api = "82"
#noinspection GradleDependency
ezXHelper = "1.0.3"
kotlin = "1.9.0"

[libraries]
xposed-api = { module = "de.robv.android.xposed:api", version.ref = "api" }
ezXHelper = { module = "com.github.kyuubiran:EzXHelper", version.ref = "ezXHelper" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

